Added testing functionality
Graffino/Graffino-Docker-Ninja pull request #29
Opened 2020-01-29 16:53 UTC by nickciolpan

ClickUp link: https://app.clickup.com/t/xxxxxx

- [ x ] Passes all regression tests
- [ x ] Is cross-browser compatible
- [ x ] Is cross-device compatible
- [ x ] Fullfils General Acceptance Criteria (see Wiki)
- [ x ] Fullfils Specific Acceptance Criteria (see ClickUp car)
- [ ] Adheres to code standards
- [ ] All code review has been addressed
- [ ] No linting errors

TODO:

- [ ] Test against Design files functionality
- [ ] Run Selenium in a background job
- [ ] Add Safari headless browser
- [ ] Add our most supported breakpoints
- [ ] Write documentation

To understand how to fill in the above, see: https://wiki.graffino.net/doc/quality-assurance-KPkwZGTCJj

2020-01-29 18:55 UTC, zenopopovici requested changes

2020-01-29 18:55 UTC, zenopopovici commented on .hermione.conf.js
> +  screenshotsDir: 'tests/hermione/screens',
Clearer name for reports?

2020-01-29 18:55 UTC, zenopopovici commented on .hermione.conf.js
> +    // safariXL: {
Remove comments

2020-01-29 18:55 UTC, zenopopovici commented on package.json
> +    "test-prep": "./node_modules/.bin/selenium-standalone install && ./node_modules/.bin/selenium-standalone start",
`test-setup` would be a clearer name as we have `wp-setup` ...

2020-01-29 18:55 UTC, zenopopovici commented on package.json
> +    "approve": "node node_modules/hermione/bin/hermione --update-refs",
should be `test-approve`

2020-01-30 14:54 UTC, nickciolpan commented
@zenopopovici Merge this please if nothing else.

2020-01-30 15:10 UTC, pauljugarean approved these changes

2020-01-30 15:17 UTC, zenopopovici approved these changes

2020-01-30 15:19 UTC, merged