[Feature] Init Scripts
Graffino/Graffino-Docker-Ninja pull request #40
Opened 2020-05-22 10:44 UTC by pauljugarean

# Pull Request

ClickUp link: <https://app.clickup.com/t/5amjq7>

## Acceptance criteria

* [ ] Passes all regression tests
* [ ] Is cross-browser compatible
* [ ] Is cross-device compatible
* [ ] Fullfils General Acceptance Criteria (see Wiki)
* [ ] Fullfils Specific Acceptance Criteria (see ClickUp card)
* [ ] Adheres to code standards
* [ ] All code reviews have been addressed
* [ ] No linting errors

QA Wiki: [Generic Criteria](https://wiki.graffino.net/doc/generic-criteria-kHpwt8jdKP)

2020-07-28 11:18 UTC, zenopopovici requested changes

2020-07-28 11:18 UTC, zenopopovici commented on src/views/layout/header.handlebars
> +  <meta name="twitter:title" content="Graffino proiectu">
```suggestion
  <meta name="twitter:title" content="{{package 'name'}}">
```

2020-09-30 09:14 UTC, Cbooogdan requested changes

2020-09-30 09:14 UTC, Cbooogdan commented on src/views/layout/header.handlebars
> +  <meta name="apple-mobile-web-app-title" content="{{package 'description'}}">
Cred ca ar trebui sa fie {{package 'name'}}

2020-09-30 11:43 UTC, zenopopovici commented on bin/clean-ninja.js
> +  await fs.remove(path.resolve(__dirname, '../src/static/touch-startup-image.png'))
Vezi ca nu-i bine ce faci. Ar trebui sa inlocuiesti astea cu placeholder files (mai ales in static unde oamenii tb sa genereze favicons si socials si trebuie sa aiba un starting point. 

La fel, cred ca in majoritatea folderelor alea trebuie sa fie ceva sa nu dea eroare la build.

2020-09-30 11:43 UTC, zenopopovici commented on bin/clean-ninja.js
> +  // clean images, icons and fonts
Comentariile incep cu litera mare.

2020-10-01 08:43 UTC, zenopopovici commented
Task linked: [TEAM-145 Ninja Init Script](https://app.clickup.com/t/2421429/TEAM-145)

2020-10-08 16:16 UTC, zenopopovici commented
Merged.

2020-10-08 16:16 UTC, closed without merging